Repository kyma-project/warden, pull requests merged in 2022-12, with the labels that each got.

#6 Helm chart
  charts/warden/.helmignore
  charts/warden/Chart.yaml
  charts/warden/templates/NOTES.txt
  charts/warden/templates/_helpers.tpl
  charts/warden/templates/deployment.yaml
  charts/warden/templates/leader-election.yaml
  charts/warden/templates/metrics-reader.yaml
  charts/warden/templates/rbac.yaml
  charts/warden/templates/service.yaml
  charts/warden/templates/serviceaccount.yaml
  charts/warden/templates/tests/test-connection.yaml
  charts/warden/values.yaml
  config/default/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/pod_controller.go
Labels: size/XL, lgtm

#7 Bump dependencies
  go.mod
  go.sum
Labels: size/S, lgtm

#4 Implementation of verification of pod images with Notary API
  charts/warden/templates/deployment.yaml
  charts/warden/values.yaml
  controllers/pod_controller.go
  go.mod
  go.sum
  main.go
  pkg/validate/service.go
Labels: size/L, lgtm

#8 fixing temporary dir and rbacs
  charts/warden/templates/rbac.yaml
  charts/warden/values.yaml
  pkg/validate/notary.go
Labels: size/XS, lgtm

#9 Add defining allowed registries
  charts/warden/templates/deployment.yaml
  charts/warden/values.yaml
  main.go
  pkg/validate/notary.go
  pkg/validate/service.go
Labels: size/M, lgtm

#10 Bump apimachinery dependency
  charts/warden/Chart.yaml
  go.mod
  go.sum
Labels: size/M, lgtm

#11 Bump image
  charts/warden/values.yaml
Labels: size/XS, lgtm

#13 Fix selector
  charts/warden/Chart.yaml
  charts/warden/templates/deployment.yaml
  charts/warden/templates/service.yaml
  config/rbac/role.yaml
Labels: size/S, lgtm

#14 Reduce replicaCount to 1
  charts/warden/Chart.yaml
  charts/warden/values.yaml
Labels: size/XS, lgtm

#16 Fix typo for priorityClassName
  charts/warden/templates/deployment.yaml
  charts/warden/values.yaml
Labels: size/S, lgtm

#17 Bump Warden version
  charts/warden/Chart.yaml
Labels: size/XS, lgtm

#18 Merge v0 to main
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/imagepolicy_types.go
  api/v1alpha1/validator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/warden/.helmignore
  charts/warden/Chart.yaml
  charts/warden/templates/NOTES.txt
  charts/warden/templates/_helpers.tpl
  charts/warden/templates/deployment.yaml
  charts/warden/templates/leader-election.yaml
  charts/warden/templates/metrics-reader.yaml
  charts/warden/templates/rbac.yaml
  charts/warden/templates/service.yaml
  charts/warden/templates/serviceaccount.yaml
  charts/warden/templates/tests/test-connection.yaml
  charts/warden/values.yaml
  config/crd/bases/validate.warden.kyma-project.io_imagepolicies.yaml
  config/crd/bases/validate.warden.kyma-project.io_validators.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_imagepolicies.yaml
  config/crd/patches/cainjection_in_validators.yaml
  config/crd/patches/webhook_in_imagepolicies.yaml
  config/crd/patches/webhook_in_validators.yaml
  config/default/kustomization.yaml
  config/rbac/imagepolicy_editor_role.yaml
  config/rbac/imagepolicy_viewer_role.yaml
  config/rbac/role.yaml
  config/rbac/validator_editor_role.yaml
  config/rbac/validator_viewer_role.yaml
  config/samples/validate_v1alpha1_imagepolicy.yaml
  config/samples/validate_v1alpha1_validator.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/imagepolicy_controller.go
  controllers/pod_controller.go
  controllers/suite_test.go
  controllers/validator_controller.go
  go.mod
  go.sum
  main.go
  pkg/validate/notary.go
  pkg/validate/notary_test.go
  pkg/validate/service.go
Labels: lgtm, size/XXL

#19 Add basic webhook
  .gitignore
  Makefile
  charts/warden/Chart.yaml
  charts/warden/charts/manager/Chart.yaml
  charts/warden/charts/manager/values.yaml
  charts/warden/charts/webhook/Chart.yaml
  charts/warden/charts/webhook/templates/deployment.yaml
  charts/warden/charts/webhook/templates/permissions.yaml
  charts/warden/charts/webhook/templates/secret.yaml
  charts/warden/charts/webhook/templates/service.yaml
  charts/warden/charts/webhook/templates/webhook.yaml
  charts/warden/charts/webhook/values.yaml
  charts/warden/templates/deployment.yaml
  charts/warden/values.yaml
  cmd/manager/main.go
  cmd/webhook/main.go
  docker/manager/Dockerfile
  docker/webhook/Dockerfile
  go.mod
  go.sum
  hack/webhook-local/.gitignore
  hack/webhook-local/Makefile
  hack/webhook-local/dockerfile.haproxy
  hack/webhook-local/get-webhook-certs.sh
  hack/webhook-local/haproxy.cfg.tpl
  hack/webhook-local/webhook-proxy.yaml.tpl
  internal/config.go
  internal/controllers/pod_controller.go
  internal/controllers/suite_test.go
  internal/webhook/certs/cert.go
  internal/webhook/certs/config.go
  internal/webhook/certs/controller.go
  internal/webhook/certs/webhook.go
  internal/webhook/config.go
  internal/webhook/defaulting/webhook.go
  internal/webhook/validation/validate.go
  pkg/.DS_Store
  pkg/validate/.DS_Store
Labels: lgtm, size/XXL
