Repository kyma-project/warden, pull requests merged in 2023-05, with the labels that each got.

#94 Add auto-rollout of warden workloads upon helm upgrade
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
  internal/validate/image_test.go
  tests/operator_test.go
Labels: size/S, lgtm

#95 Bump images
  charts/warden/values.yaml
Labels: size/XS, lgtm

#96 Release rollout warden workloads
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
  internal/validate/image_test.go
  tests/operator_test.go
Labels: size/S, lgtm

#97 Add watcher
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  hack/config.yaml
  internal/config/watcher.go
Labels: size/M, lgtm

#98 use post main images
  charts/warden/values.yaml
Labels: size/XS, lgtm
