Repository kyma-project/warden, pull requests merged in 2023-10, with the labels that each got.

#113 Sec scanners config
  sec-scanners-config.yaml
Labels: area/security, size/S, lgtm

#107 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm

#118 Add possibility to export cover out file
  Makefile
Labels: size/XS, lgtm

#117 Refactor webhook secret strategy
  .gitignore
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/admission/templates/rbac.yaml
  charts/warden/charts/admission/templates/secret.yaml
  charts/warden/values.yaml
  cmd/admission/main.go
  internal/env/env.go
  internal/env/env_test.go
  internal/webhook/certs/cert.go
  internal/webhook/certs/controller.go
  internal/webhook/certs/file.go
Labels: size/L, lgtm

#119 Add unit tests for the `certs` package
  charts/warden/values.yaml
  cmd/admission/main.go
  internal/webhook/certs/cert_test.go
  internal/webhook/certs/file_test.go
  internal/webhook/config.go
  internal/webhook/controller.go
  internal/webhook/webhook.go
Labels: kind/cleanup, area/tests, size/L, lgtm

#120 Bump golang
  charts/warden/values.yaml
  docker/admission/Dockerfile
  docker/operator/Dockerfile
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: size/M, lgtm

#122 Use prod warden images
  charts/warden/values.yaml
Labels: size/XS, lgtm

#124 Bump images
  charts/warden/values.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#123 add running module locally
  .gitignore
  hack/run-module-locally.sh
  module-config-template.yaml
Labels: size/M, lgtm

#125 Warden module generate
  Makefile
  hack/create-module.sh
  hack/get_helm_file_name.sh
  hack/get_kyma_file_name.sh
  hack/run-module-locally.sh
Labels: kind/feature, size/L, lgtm, area/ci

#128 Fix read only dir
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
Labels: size/S, lgtm

#129 Fix read only dir
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
Labels: size/S, lgtm

#130 add enter
  cmd/admission/main.go
Labels: size/XS, lgtm
