Repository kyma-project/warden, pull requests merged in 2023-01, with the labels that each got.

#21 add integration tests for operator
  Makefile
  charts/warden/charts/operator/templates/deployment.yaml
  docker/admission/Dockerfile
  docker/operator/Dockerfile
  go.mod
  internal/controllers/pod_controller.go
  pkg/labels.go
  tests/go.mod
  tests/go.sum
  tests/helpers/namespace_builder.go
  tests/helpers/pod_builder.go
  tests/helpers/test_context.go
  tests/operator_test.go
Labels: lgtm, size/XXL

#22 Validate tests
  charts/warden/values.yaml
  go.mod
  go.sum
  internal/validate/mock_notary.go
  internal/validate/notary.go
  internal/validate/notary_test.go
  internal/validate/service.go
  internal/validate/service_test.go
  tests/go.mod
  tests/go.sum
Labels: size/L, lgtm

#23 Enable validation on default webhook
  .gitignore
  Makefile
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  go.mod
  go.sum
  internal/admission/defaulting.go
  internal/admission/validation.go
  internal/controllers/pod_controller.go
  internal/validate/image.go
  internal/validate/image_test.go
  internal/validate/mock_notary.go
  internal/validate/mocks/ImageValidatorService.go
  internal/validate/notary.go
  internal/validate/pod.go
  internal/validate/pod_test.go
  internal/webhook/certs/webhook.go
  internal/webhook/config.go
  internal/webhook/defaulting/webhook.go
  pkg/labels.go
Labels: size/XL, lgtm

#25 Enable validation webhook
  .gitignore
  Makefile
  charts/warden/values.yaml
  cmd/admission/main.go
  internal/admission/defaulting.go
  internal/admission/validation.go
  internal/admission/validation_test.go
  internal/controllers/pod_controller.go
  internal/util/sets/strings.go
  internal/validate/pod.go
  pkg/labels.go
  tests/operator_test.go
Labels: size/L, lgtm

#27 Fix validation webhook
  charts/warden/values.yaml
  go.mod
  go.sum
  internal/admission/defaulting.go
  internal/admission/validation.go
  internal/admission/validation_test.go
Labels: size/S, lgtm

#26 Use Pod Validator Service in reconcile
  cmd/operator/main.go
  go.mod
  go.sum
  internal/controllers/controller_test.go
  internal/controllers/pod_controller.go
  internal/controllers/suite_test.go
  internal/validate/mocks/PodValidator.go
Labels: size/L, lgtm

#29 Add timeout for defaulting webhook
  cmd/admission/main.go
  cmd/operator/main.go
  go.mod
  go.sum
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/config.go
  internal/controllers/controller_test.go
  internal/controllers/pod_controller.go
  internal/validate/image.go
  internal/validate/image_test.go
  internal/validate/mock_notary.go
  internal/validate/mocks/ImageValidatorService.go
  internal/validate/notary.go
  internal/validate/notary_test.go
  internal/validate/pod.go
  internal/validate/pod_test.go
  internal/webhook/config.go
  pkg/labels.go
  tests/go.mod
  tests/go.sum
Labels: size/XL, lgtm

#33 Wait for helm install and uninstall
  Makefile
Labels: size/XS, lgtm

#35 Remove invalid unit test
  internal/validate/pod_test.go
Labels: size/M, lgtm

#30 Load warden configuration from file
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/templates/configmap.yaml
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  internal/config/file.go
  internal/config/file_test.go
  internal/config/testData/config.yaml
  internal/validate/image.go
  internal/validate/parse.go
  internal/validate/parse_test.go
  internal/webhook/config.go
Labels: area/serverless, size/L, lgtm

#36 Unify components args
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/templates/configmap.yaml
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  hack/config.yaml
  internal/config/file.go
  internal/webhook/config.go
Labels: size/L, lgtm

#37 Fix for webhook
  charts/warden/values.yaml
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/admission/validation.go
  internal/admission/validation_test.go
  internal/validate/notary.go
Labels: size/M, lgtm

#40 Use right prod images
  charts/warden/values.yaml
Labels: size/XS, lgtm

#39 better logging
  charts/warden/values.yaml
  internal/admission/defaulting.go
  internal/helpers/log_helpers.go
  internal/validate/image.go
  internal/validate/pod.go
Labels: size/L, lgtm
