Repository kyma-project/warden, pull requests merged in 2023-02, with the labels that each got.

#41 Add namespace ctrl
  charts/warden/values.yaml
  cmd/operator/main.go
  internal/controllers/controller_test.go
  internal/controllers/namespace/controller.go
  internal/controllers/namespace/controller_test.go
  internal/controllers/namespace/label.go
  internal/controllers/namespace/label_test.go
  internal/controllers/namespace/predicate.go
  internal/controllers/namespace/predicate_test.go
  internal/controllers/test_suite/suite.go
  internal/validate/notary_test.go
Labels: size/XL, lgtm

#43 Add logging logic to validation webhook
  charts/warden/values.yaml
  cmd/admission/main.go
  internal/admission/decorators.go
  internal/admission/defaulting.go
  internal/admission/validation.go
  internal/admission/validation_test.go
  internal/controllers/namespace/controller_test.go
  internal/controllers/namespace/predicate_test.go
  internal/test_helpers/logger.go
Labels: size/L, lgtm

#50 Disable istio sidecar for admission
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/values.yaml
Labels: size/XS, lgtm

#48 Configurable requeue period
  charts/warden/values.yaml
  cmd/operator/main.go
  internal/config/file.go
  internal/controllers/controller_test.go
  internal/controllers/pod_controller.go
Labels: size/M, lgtm

#53 Use buffered channel for timeout
  charts/warden/values.yaml
  internal/admission/decorators.go
  internal/admission/defaulting_test.go
  internal/validate/image.go
Labels: size/S, lgtm

#46 Unify logging using lib from kyma
  Makefile
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  go.mod
  go.sum
  internal/admission/decorators.go
  internal/config/file.go
  internal/controllers/pod_controller.go
  internal/helpers/log_helpers.go
  internal/logging/setup.go
Labels: size/L, lgtm

#52 Validation
  charts/warden/values.yaml
  internal/validate/image.go
  internal/validate/image_test.go
  internal/validate/pod.go
  internal/validate/pod_test.go
  pkg/errors.go
Labels: size/L, lgtm

#58 Prepare new releease candidate.
  Makefile
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  go.mod
  go.sum
  internal/admission/decorators.go
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/config/file.go
  internal/controllers/controller_test.go
  internal/controllers/namespace/controller.go
  internal/controllers/pod_controller.go
  internal/helpers/log_helpers.go
  internal/logging/setup.go
  internal/validate/image.go
  internal/validate/image_test.go
  internal/validate/pod.go
  internal/validate/pod_test.go
  pkg/errors.go
Labels: size/XL, lgtm

#59 Fix error handling
  charts/warden/values.yaml
  internal/validate/image.go
  internal/validate/image_test.go
  internal/validate/notary.go
  internal/validate/pod.go
  internal/validate/pod_test.go
  pkg/errors.go
  pkg/errors_test.go
Labels: size/L, lgtm

#57 Unify labels
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/admission/templates/secret.yaml
  charts/warden/charts/admission/templates/service.yaml
  charts/warden/charts/operator/templates/_helpers.tpl
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/charts/operator/templates/service.yaml
  charts/warden/values.yaml
Labels: size/M, lgtm

#62 Update 0.2
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/admission/templates/secret.yaml
  charts/warden/charts/admission/templates/service.yaml
  charts/warden/charts/operator/templates/_helpers.tpl
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/charts/operator/templates/service.yaml
  charts/warden/values.yaml
  internal/validate/image.go
  internal/validate/image_test.go
  internal/validate/notary.go
  internal/validate/pod.go
  internal/validate/pod_test.go
  pkg/errors.go
  pkg/errors_test.go
Labels: size/L, lgtm

#63 Use post main images
  charts/warden/values.yaml
Labels: size/XS, lgtm

#54 Namespace controller integration test
  tests/helpers/pod_builder.go
  tests/namespace_test.go
Labels: size/L, lgtm

#65 Fix names in warden chart
  charts/warden/charts/admission/templates/webhook.yaml
  charts/warden/charts/operator/templates/_helpers.tpl
  charts/warden/charts/operator/templates/leader-election.yaml
  charts/warden/charts/operator/templates/metrics-reader.yaml
  charts/warden/templates/tests/test-connection.yaml
Labels: size/M, lgtm

#68 Update Chart
  charts/warden/charts/admission/templates/webhook.yaml
  charts/warden/charts/operator/templates/_helpers.tpl
  charts/warden/charts/operator/templates/leader-election.yaml
  charts/warden/charts/operator/templates/metrics-reader.yaml
  charts/warden/templates/tests/test-connection.yaml
  tests/helpers/pod_builder.go
  tests/namespace_test.go
Labels: size/L, lgtm

#44 Add strict mode
  charts/warden/values.yaml
  cmd/admission/main.go
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/config/file.go
Labels: size/L, lgtm

#66 Allow scheduling pods when validation timeouts.
  charts/warden/values.yaml
  internal/admission/decorators.go
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
Labels: size/M, lgtm

#64 Admission flow for create pod
  charts/warden/values.yaml
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
Labels: size/L, lgtm

#67 Small improvemetns for logs
  charts/warden/values.yaml
  internal/admission/defaulting.go
  internal/admission/validation.go
  internal/helpers/log_helpers.go
  internal/validate/image.go
Labels: size/M, lgtm

#69 Improve tests
  Makefile
  charts/warden/values.yaml
  internal/validate/image_test.go
  internal/validate/mock_notary.go
  internal/validate/mocks/NotaryRepoClient.go
  internal/validate/mocks/RepoFactory.go
  internal/validate/notary.go
  tests/namespace_test.go
  tests/operator_test.go
Labels: size/XL, lgtm

#70 Admission flow reject
  charts/warden/values.yaml
  internal/admission/annotations.go
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/admission/validation.go
  internal/admission/validation_test.go
  pkg/labels.go
Labels: size/L, lgtm

#74 Unblock defaulting webhook
  charts/warden/values.yaml
  internal/admission/decorators.go
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/validate/image_test.go
Labels: size/M, lgtm

#75 use post main images
  charts/warden/values.yaml
Labels: size/XS, lgtm

#60 Describe how to release warden
  README.md
Labels: size/S, lgtm

#73 change way of checking image changes in pod
  charts/warden/values.yaml
  internal/controllers/controller_test.go
  internal/controllers/pod_controller.go
Labels: size/L, lgtm
