Repository kyma-project/warden, pull requests merged in 2023-11, with the labels that each got.

#132 Test LM Integration
  Makefile
  hack/create-module.sh
  hack/run-module-locally.sh
  hack/verify_warden_status.sh
Labels: kind/feature, size/M, lgtm, area/ci

#134 Removed tput and added git origin configuration
  Makefile
  hack/run-module-locally.sh
Labels: size/S, lgtm

#135 Change script to watch warden deployment
  Makefile
  hack/verify_warden_status.sh
Labels: kind/bug, size/S, lgtm

#136 Sec scanners config latest tags
  docker/admission/Dockerfile
  docker/operator/Dockerfile
  hack/create-module.sh
  module-config-template.yaml
  sec-scanners-config.yaml
Labels: kind/feature, area/security, size/S, lgtm

#137 add configuration for golangci-lint
  .golangci.yaml
Labels: kind/cleanup, size/S, lgtm, area/ci

#138 fix errors showed by linters
  internal/webhook/certs/cert.go
Labels: kind/failing-test, size/XS, lgtm

#139 Add missing issue,PR templates and stale config
  .github/issue-template.md
  .github/pull-request-template.md
  .github/stale.yml
  .github/workflows/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/ISSUE_TEMPLATE/decision-record.md
  .github/workflows/ISSUE_TEMPLATE/documentation-improvement.md
  .github/workflows/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
  .github/workflows/ISSUE_TEMPLATE/security-vulnerability.md
Labels: size/L, lgtm

#140 Remove workflows directory and stale.yaml
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/decision-record.md
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  .github/stale.yml
Labels: size/S, lgtm
