Repository kyma-project/warden, pull requests merged in 2023-03, with the labels that each got.

#78 Operator unit tests
  charts/warden/values.yaml
  internal/admission/defaulting_test.go
  internal/controllers/pod_controller.go
  internal/controllers/pod_controller_test.go
Labels: size/L, lgtm

#80 Fix endless reconciliation
  charts/warden/values.yaml
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/admission/validation.go
  internal/controllers/namespace/controller.go
Labels: size/L, lgtm

#81 upgrade golang.org/x/net to v0.7.0
  go.mod
  go.sum
Labels: size/S, lgtm

#82 bump image
  charts/warden/values.yaml
  internal/validate/pod.go
  tests/go.mod
  tests/go.sum
Labels: size/L, lgtm

#84 Prepare next patch release
  README.md
  charts/warden/values.yaml
  go.mod
  go.sum
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/admission/validation.go
  internal/controllers/controller_test.go
  internal/controllers/namespace/controller.go
  internal/controllers/pod_controller.go
  internal/controllers/pod_controller_test.go
  internal/validate/pod.go
  tests/go.mod
  tests/go.sum
Labels: size/XL, lgtm

#86 Set high priority class name for warden workloads
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
Labels: kind/bug, size/XS, lgtm

#88 Define resources for containers
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
Labels: size/S, lgtm

#89 Release 0.3 patch
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/operator/templates/deployment.yaml
  charts/warden/values.yaml
Labels: size/M, lgtm

#90 revert images
  charts/warden/values.yaml
Labels: size/XS, lgtm

#91 increase memory
  charts/warden/values.yaml
Labels: size/XS, lgtm
