Repository kyma-project/warden, pull requests merged in 2023-12, with the labels that each got.

#144 Change images to empty list in protocode
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#147 Add images for protocode
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#148 add license file
  LICENSE
Labels: area/tooling, size/L, lgtm, kind/chore, cla: yes

#150 Possibility to configure single whitelist entries via dedicated override
  charts/warden/Chart.yaml
  charts/warden/charts/admission/templates/deployment.yaml
  charts/warden/charts/admission/templates/webhook.yaml
  charts/warden/templates/configmap.yaml
  charts/warden/templates/priorityclass.yaml
  charts/warden/values.yaml
Labels: kind/feature, size/M, lgtm, cla: yes

#153 Add to codeowners
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#152 Rename subchart folders
  charts/warden/Chart.yaml
  charts/warden/charts/warden-admission/Chart.yaml
  charts/warden/charts/warden-admission/templates/deployment.yaml
  charts/warden/charts/warden-admission/templates/rbac.yaml
  charts/warden/charts/warden-admission/templates/service.yaml
  charts/warden/charts/warden-admission/templates/webhook.yaml
  charts/warden/charts/warden-admission/values.yaml
  charts/warden/charts/warden-operator/Chart.yaml
  charts/warden/charts/warden-operator/templates/NOTES.txt
  charts/warden/charts/warden-operator/templates/deployment.yaml
  charts/warden/charts/warden-operator/templates/leader-election.yaml
  charts/warden/charts/warden-operator/templates/rbac.yaml
  charts/warden/charts/warden-operator/templates/service.yaml
  charts/warden/charts/warden-operator/templates/serviceaccount.yaml
  charts/warden/charts/warden-operator/values.yaml
  charts/warden/values.yaml
Labels: kind/cleanup, size/XS, lgtm, cla: yes

#155 Bump golang runtime 1.21.5
  docker/admission/Dockerfile
  docker/operator/Dockerfile
Labels: size/XS, lgtm, kind/chore, cla: yes

#156 Disable admission by default
  Makefile
  charts/warden/values.yaml
  hack/create-module.sh
Labels: kind/feature, size/S, lgtm, cla: yes

#158 bump warden images
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes
