Repository kyma-project/warden, pull requests merged in 2024-11, with the labels that each got.

#336 Predefined user allowed registries
  charts/warden/templates/configmap.yaml
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  docs/contributor/01-10-configure_system.md
  internal/admission/defaulting_test.go
  internal/config/file.go
  internal/config/file_test.go
  internal/config/testData/config.yaml
  internal/validate/pod.go
Labels: size/M, lgtm, cla: yes

#335 Add support for ImagePullSecrets
  cmd/admission/main.go
  cmd/operator/main.go
  go.mod
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/controllers/pod_controller.go
  internal/controllers/pod_controller_test.go
  internal/helpers/pull_credentials.go
  internal/helpers/pull_credentials_test.go
  internal/validate/common_test.go
  internal/validate/image.go
  internal/validate/image_internal_test.go
  internal/validate/image_test.go
  internal/validate/mocks/ImageValidatorService.go
  internal/validate/mocks/NotaryRepoClient.go
  internal/validate/mocks/PodValidator.go
  internal/validate/mocks/RepoFactory.go
  internal/validate/mocks/ValidatorSvcFactory.go
  internal/validate/pod.go
  internal/validate/pod_test.go
Labels: size/XL, lgtm, cla: yes

#340 Skip allowed prefixes before parsing
  internal/validate/image.go
  internal/validate/image_test.go
Labels: size/S, lgtm, cla: yes

#341 Skip allowed prefixes before parsing (#340)
  internal/validate/image.go
  internal/validate/image_test.go
Labels: size/S, lgtm, cla: yes

#342 Fix image name parsing
  internal/admission/defaulting_test.go
  internal/validate/image.go
  internal/validate/image_test.go
Labels: size/M, lgtm, cla: yes

#347 Bump k8s version
  .github/actions/create-k3d-cluster/action.yaml
  Makefile
Labels: size/S, lgtm, cla: yes

#346 Bump Go dependencies
  cmd/admission/main.go
  go.mod
  go.sum
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/admission/validation.go
  internal/admission/validation_test.go
  internal/webhook/controller.go
Labels: size/L, cla: yes

#352 Add secret rbac for warden operator
  charts/warden/charts/warden-operator/templates/rbac.yaml
  config/rbac/role.yaml
  internal/controllers/namespace/controller.go
  internal/controllers/pod_controller.go
Labels: kind/bug, size/S, lgtm, cla: yes

#354 Add secret rbac for warden operator (#352)
  charts/warden/charts/warden-operator/templates/rbac.yaml
  config/rbac/role.yaml
  internal/controllers/namespace/controller.go
  internal/controllers/pod_controller.go
Labels: kind/bug, size/S, lgtm, cla: yes
