Repository kyma-project/warden, pull requests merged in 2024-09, with the labels that each got.

#269 Add code of conduct and contributing docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: size/M, lgtm, cla: yes

#271 Automatically deduce go version
  .github/actions/setup-go/action.yaml
Labels: size/XS, lgtm, cla: yes

#272 Unify linter config
  .golangci.yaml
Labels: size/XS, cla: yes

#275 Specify target ref for pull_request_target workflows
  .github/actions/rebase/action.yaml
  .github/workflows/_build.yaml
  .github/workflows/_gitleaks.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/_unit-tests.yaml
  .github/workflows/lint.yaml
Labels: size/M, kind/failing-test, area/tests, cla: yes

#276 Bump minimum Go versino to 1.22
  go.mod
Labels: size/XS, cla: yes

#278 Fix typo in workflow name
  .github/workflows/push.yaml
Labels: size/XS, lgtm, cla: yes

#277 Bump base golang image
  docker/admission/Dockerfile
  docker/operator/Dockerfile
Labels: size/XS, cla: yes

#279 Fix controller-gen target to correctly detect version #188
  Makefile
Labels: size/XS, lgtm, cla: yes
