Repository kyma-project/warden, pull requests merged in 2024-04, with the labels that each got.

#203 Remove explicit link usage
  .github/workflows/promote-to-release-channel-with-config.yaml
Labels: kind/bug, size/XS, lgtm, cla: yes

#206 enable Dependabot
  .github/dependabot.yml
Labels: size/M, lgtm, cla: yes

#205 Use single go.mod file
  tests/go.mod
  tests/go.sum
  tests/namespace_test.go
  tests/warden_test.go
Labels: size/L, lgtm, cla: yes

#214 Remove differences between warden and serverless repos
  .github/scripts/release-draft.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, area/ci, kind/chore, cla: yes

#215 Add Halamix2 to codeowners
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#216 Add missing space
  .github/scripts/release-assets.sh
Labels: kind/bug, size/XS, lgtm, area/ci, cla: yes

#204 Enable gitleaks check
  .github/workflows/pull-gitleaks.yaml
Labels: size/S, lgtm, area/ci, cla: yes

#217 Update deprecated Port fields
  cmd/operator/main.go
Labels: size/S, lgtm, cla: yes

#218 bump docker
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#224 Test with k8s v1.29.3
  .github/workflows/upgrade-test.yaml
  .github/workflows/warden-verify.yaml
Labels: size/XS, lgtm, kind/chore, cla: yes

#226 fix image building under ADO
  docker/admission/Dockerfile
  docker/operator/Dockerfile
Labels: size/XS, lgtm, cla: yes

#225 Bump k8s to 0.29
  cmd/admission/main.go
  cmd/operator/main.go
  go.mod
  go.sum
Labels: size/L, lgtm, cla: yes
