Repository kyma-project/warden, pull requests merged in 2024-02, with the labels that each got.

#188 Enable cache only for 1 object
  cmd/admission/main.go
  internal/webhook/controller.go
Labels: size/S, lgtm, cla: yes

#187 Install Warden from release not from tag for upgrade-test
  .github/workflows/upgrade-test.yaml
Labels: size/XS, lgtm, cla: yes

#189 Use correct make target
  .github/workflows/upgrade-test.yaml
Labels: size/XS, lgtm, cla: yes

#190 Cleanup makefile
  .github/workflows/warden-verify.yaml
  Makefile
Labels: size/L, lgtm, cla: yes

#191 Bump k8s
  .github/workflows/warden-verify.yaml
  Makefile
  cmd/admission/main.go
  cmd/operator/main.go
  go.mod
  go.sum
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/admission/validation.go
  internal/admission/validation_test.go
  internal/webhook/controller.go
  internal/webhook/webhook.go
  tests/go.mod
  tests/go.sum
Labels: lgtm, size/XXL, cla: yes

#192 Warden admission control for labelled namespaces only as per webhook configuration
  charts/warden/charts/warden-admission/templates/webhook.yaml
  internal/webhook/webhook.go
  tests/helpers/test_context.go
Labels: size/M, lgtm, cla: yes

#193 Fix warden webhooks-patch-0.5
  charts/warden/charts/admission/templates/webhook.yaml
  internal/webhook/certs/webhook.go
  tests/helpers/test_context.go
Labels: size/M, lgtm, cla: yes

#194 Fix warden webhooks-patch-0.5 bump
  charts/warden/values.yaml
Labels: size/XS, lgtm, cla: yes

#195 Fix warden validation webhook name for reconciler tracker
  charts/warden/charts/admission/templates/webhook.yaml
Labels: size/XS, lgtm, cla: yes

#196 Test warden on k8s 1.28.6
  .github/workflows/upgrade-test.yaml
  .github/workflows/warden-verify.yaml
Labels: lgtm, kind/chore, cla: yes

#197 Bump sec scanner rc tag
  sec-scanners-config.yaml
Labels: size/XS, lgtm, kind/chore, cla: yes

#199 Cleanup readme
  README.md
Labels: size/M, kind/cleanup, area/documentation, lgtm, cla: yes

#200 Stop using /common/logging from kyma monorepo
  go.mod
  go.sum
  internal/logging/logger/format.go
  internal/logging/logger/format_test.go
  internal/logging/logger/level.go
  internal/logging/logger/level_test.go
  internal/logging/logger/logger.go
  internal/logging/logger/logger_test.go
  internal/logging/setup.go
  internal/logging/tracing/helper.go
  internal/logging/tracing/helper_test.go
  internal/logging/tracing/middleware.go
  internal/logging/tracing/middleware_test.go
Labels: kind/cleanup, size/XL, lgtm, cla: yes
