Repository kyma-project/warden, pull requests merged in 2024-01, with the labels that each got.

#160 Rename post verify target for warden
  .gitignore
  Makefile
  hack/create-module.sh
  hack/run-module-locally.sh
Labels: size/L, lgtm, cla: yes

#162 Run integration test on gh action
  .github/workflows/k3d-verify-warden-manifest.yaml
  Makefile
Labels: size/M, lgtm, cla: yes

#163 Migrate CI tests to GH actions
  .github/workflows/warden-verify.yaml
  internal/validate/pod_test.go
Labels: size/M, lgtm, cla: yes

#166 GH action release workflow
  .github/scripts/publish_release.sh
  .github/scripts/release-assets.sh
  .github/scripts/release-draft.sh
  .github/scripts/verify-actions-status.sh
  .github/scripts/verify-release-builds.sh
  .github/workflows/create-release.yaml
  Makefile
Labels: size/L, lgtm, area/ci, cla: yes

#170 Remove secrets and configmaps from the cache
  charts/warden/values.yaml
  cmd/admission/main.go
  cmd/operator/main.go
Labels: kind/feature, size/S, lgtm, cla: yes

#169 Remove project file
  PROJECT
Labels: kind/cleanup, size/XS, lgtm, cla: yes

#173 Auto image bumps for warden verify jobs
  .github/workflows/warden-verify.yaml
  Makefile
  charts/warden/values.yaml
  tests/namespace_test.go
Labels: size/M, lgtm, cla: yes

#174 Auto update image tags upon release
  .github/scripts/upgrade-chart-version.sh
  .github/scripts/upgrade-sec-scanners-config.sh
  .github/workflows/create-release.yaml
Labels: size/M, lgtm, area/ci, cla: yes

#175 Update release instructions
  CODEOWNERS
  README.md
  sec-scanners-config.yaml
  tests/warden_test.go
Labels: documentation, size/M, kind/cleanup, lgtm, cla: yes

#176 Move status badge to status subcategory
  .github/workflows/warden-verify.yaml
  README.md
Labels: kind/cleanup, area/documentation, size/S, lgtm, cla: yes

#178 Warden promotion workflow
  .github/scripts/upgrade-sec-scanners-config.sh
  .github/workflows/promote-to-release-channel-with-config.yaml
  Makefile
  module-config-template.yaml
Labels: size/L, lgtm, cla: yes

#179 Cleanup workflows
  .github/workflows/create-release.yaml
  module-config-template.yaml
Labels: kind/cleanup, lgtm, area/ci, cla: yes

#181 bump-rc-tag 0.11.1
  sec-scanners-config.yaml
Labels: size/XS, lgtm, kind/chore, cla: yes

#182 Upgrade test
  .github/workflows/upgrade-test.yaml
Labels: kind/feature, size/M, area/tests, lgtm, cla: yes

#186 Add readyz to admission
  charts/warden/charts/warden-admission/templates/deployment.yaml
  cmd/admission/main.go
Labels: size/M, lgtm, cla: yes
