Repository kyma-project/warden, pull requests merged in 2024-10, with the labels that each got.

#284 Set fixed lint action version
  .github/workflows/lint.yaml
Labels: size/XS, lgtm, area/ci, kind/chore, cla: yes

#285 fix app version in charts
  .github/scripts/upgrade-chart-version.sh
  charts/warden/Chart.yaml
  charts/warden/charts/warden-admission/Chart.yaml
  charts/warden/charts/warden-operator/Chart.yaml
Labels: size/S, lgtm, cla: yes

#281 customer verification
  .golangci.yaml
  cmd/admission/main.go
  cmd/operator/main.go
  internal/admission/defaulting.go
  internal/admission/defaulting_test.go
  internal/controllers/namespace/controller.go
  internal/controllers/namespace/predicate.go
  internal/controllers/namespace/predicate_test.go
  internal/controllers/pod_controller.go
  internal/controllers/pod_controller_test.go
  internal/helpers/user_notary_cfg.go
  internal/validate/mocks/ImageValidatorService.go
  internal/validate/mocks/NotaryRepoClient.go
  internal/validate/mocks/PodValidator.go
  internal/validate/mocks/RepoFactory.go
  internal/validate/mocks/ValidatorSvcFactory.go
  internal/validate/namespace.go
  internal/validate/namespace_test.go
  internal/validate/pod.go
  internal/validate/pod_test.go
  internal/webhook/webhook.go
  pkg/labels.go
Labels: size/XXL, cla: yes

#289 Simplify release id for assets
  .github/scripts/release-assets.sh
  .github/workflows/create-release.yaml
Labels: size/S, lgtm, cla: yes

#286 add image index support
  internal/validate/image.go
  internal/validate/image_test.go
Labels: size/L, cla: yes

#290 normalize github script names
  .github/scripts/create-draft-release.sh
  .github/scripts/publish-release.sh
  .github/scripts/release.sh
  .github/workflows/create-release.yaml
Labels: size/XS, cla: yes

#291 Tests and bump k8s from 1.29 to 1.30
  .github/actions/create-k3d-cluster/action.yaml
Labels: size/XS, lgtm, cla: yes

#292 Remove unnecessary git fetch origin
  .github/workflows/_upgrade-test.yaml
Labels: size/XS, lgtm, cla: yes

#293 Bump rc-tag
  sec-scanners-config.yaml
Labels: size/XS, cla: yes

#287 Add warden documentation
  .gitignore
  docs/assets/user_architecture.svg
  docs/assets/user_operations.svg
  docs/assets/user_reconcile.svg
  docs/contributor/00-01-overview-flow.md
  docs/contributor/00-02-architecture.md
  docs/contributor/01-10-configure_system.md
  docs/user/00-01-overview-flow.md
  docs/user/01-10-configure-user.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/tutorials/01-20-use-warden-on-namespace.md
  docs/user/tutorials/README.md
Labels: size/L, cla: yes

#294 Fix release upgrade flow
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, lgtm, cla: yes

#295 Fix release upgrade flow (#294)
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, cla: yes

#299 Fix warden status check
  hack/verify_warden_status.sh
Labels: size/S, lgtm, cla: yes

#300 Add reinvocationPolicy
  charts/warden/charts/warden-admission/templates/webhook.yaml
  internal/webhook/webhook.go
Labels: size/XS, lgtm, cla: yes

#301 Move create tag job earlier in the workflow
  .github/workflows/promote-to-release-channel.yaml
  .github/workflows/push.yaml
Labels: size/M, lgtm, cla: yes

#302 Move create tag job earlier in the workflow (#301)
  .github/workflows/promote-to-release-channel.yaml
  .github/workflows/push.yaml
Labels: size/M, lgtm, cla: yes

#303 Adjust waiting for steps in promote to channel workflow
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, lgtm, cla: yes

#304 Adjust waiting for steps in promote to channel workflow (#303)
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, lgtm, cla: yes

#305 Pass tag which triggered the build job
  .github/workflows/release.yaml
Labels: size/XS, cla: yes

#306 Change regexp to github actions syntax
  .github/workflows/release.yaml
Labels: size/XS, lgtm, cla: yes

#307 Change regexp to github actions syntax
  .github/workflows/release.yaml
Labels: size/XS, cla: yes

#309 Add reinvocationPolicy (#300)
  charts/warden/charts/warden-admission/templates/webhook.yaml
  internal/webhook/webhook.go
Labels: size/XS, cla: yes

#310 Cherry pick of github workflows
  .github/actions/create-k3d-cluster/action.yaml
  .github/actions/setup-go/action.yaml
  .github/scripts/create-draft-release.sh
  .github/scripts/publish-release.sh
  .github/scripts/release.sh
  .github/scripts/upgrade-chart-version.sh
  .github/workflows/_build.yaml
  .github/workflows/_gitleaks.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/_unit-tests.yaml
  .github/workflows/_upgrade-test.yaml
  .github/workflows/create-release.yaml
  .github/workflows/lint.yaml
  .github/workflows/promote-to-release-channel.yaml
  .github/workflows/pull.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  .github/workflows/upgrade-test.yaml
  .github/workflows/warden-verify.yaml
Labels: size/XL, lgtm, cla: yes

#312 fix image building in 0.12
  docker/admission/Dockerfile
  docker/operator/Dockerfile
Labels: size/XS, lgtm, cla: yes

#313 Revert moving tag
  .github/workflows/promote-to-release-channel.yaml
Labels: size/M, lgtm, cla: yes

#316 Remove prow status check
  .github/scripts/verify-release-builds.sh
  .github/workflows/promote-to-release-channel.yaml
Labels: size/M, cla: yes

#315 Cherry pick rm prow status
  .github/scripts/verify-release-builds.sh
  .github/workflows/promote-to-release-channel.yaml
Labels: size/M, lgtm, cla: yes

#314 Adjust promote
  .github/scripts/verify-release-builds.sh
  .github/workflows/promote-to-release-channel.yaml
Labels: size/M, lgtm, cla: yes

#317 increase operator memory limit
  charts/warden/values.yaml
Labels: size/XS, lgtm, cla: yes

#318 Fix release channel job permissions
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, cla: yes

#320 cherry pick: increase operator memory limit
  charts/warden/values.yaml
Labels: size/XS, lgtm, cla: yes

#319 cherry-pick: increase operator memory limit
  charts/warden/values.yaml
Labels: size/XS, lgtm, cla: yes

#322 Fix release channel job permissions (#318)
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, cla: yes

#321 Fix release channel job permissions (#318)
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, cla: yes

#308 Update release config hint
  .github/workflows/promote-to-release-channel.yaml
Labels: size/XS, cla: yes

#323 increase operator memory limit
  charts/warden/values.yaml
Labels: size/XS, cla: yes

#324 cherry-pick: increase operator memory limit
  charts/warden/values.yaml
Labels: size/XS, lgtm, cla: yes

#325 cherry-pick: increase operator memory limit
  charts/warden/values.yaml
Labels: size/XS, lgtm, cla: yes

#326 disable istio sidecar for operator
  charts/warden/charts/warden-admission/templates/deployment.yaml
  charts/warden/charts/warden-operator/templates/deployment.yaml
Labels: size/XS, cla: yes

#327 cherry-pick: disable istio sidecar for operator
  charts/warden/charts/warden-admission/templates/deployment.yaml
  charts/warden/charts/warden-operator/templates/deployment.yaml
Labels: size/XS, cla: yes

#328 Disable Istio Injection
  charts/warden/charts/warden-admission/templates/deployment.yaml
  charts/warden/charts/warden-operator/templates/deployment.yaml
Labels: size/XS, lgtm, cla: yes

#329 cherry-pick: Disable Istio Injection (#328)
  charts/warden/charts/warden-admission/templates/deployment.yaml
  charts/warden/charts/warden-operator/templates/deployment.yaml
Labels: size/XS, lgtm, cla: yes
